name: Bygg alle brancher

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!release/*'
      - '!master'

jobs:
  bygg:
    name: 'Bygg alle brancher'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1

      - name: 'Java 17'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: 'Setter Image'
        run: echo "IMAGE=ghcr.io/${{ github.repository }}/eessi-pensjon-journalforing:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV


      - name: 'Bygg og publiser docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=CET
          ./gradlew build
          docker build --tag ${{ env.IMAGE }} .
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}
