name: Bygg og deploy Q2

on:
  push:
    branches:
      - master
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # SETTER DATO OG COMMIT VARIABEL
      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      # SETTER IMAGE VARIABEL
      - name: 'Setter Image'
        run: echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-journalforing:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      # JAVA 11
      - name: 'Java 11'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      # BYGGER DOCKER CONTAINER
      - name: 'Bygg og publiser docker image'
        run: |
          ./gradlew build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # DEPLOYER TIL NAIS Q2
      - name: 'Deploy to NAIS'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-q2.yml
          VARS: nais/dev-fss-q2.json
          IMAGE: ${{ env.IMAGE }}

      # OPPRETTER GIT TAG
      - name: 'Opprett git tag'
        run: |
          curl -v -s -X POST https://api.github.com/repos/navikt/eessi-pensjon-journalforing/git/refs -H "Authorization: token  ${{ secrets.GITHUB_TOKEN }}" -d '{ "ref": "refs/tags/${{ env.DATE }}---${{ env.COMMIT_HASH }}",  "sha": "${{ env.COMMIT_HASH }}" }'

      - name: 'Repository Dispatch PROD'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-prod
          client-payload: '{"image": "${{ env.IMAGE }}"}'

      - name: 'Repository Dispatch Q1'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-q1
          client-payload: '{"image": "${{ env.IMAGE }}"}'

      # DEPLOYER TIL NAIS Q2 team namespace
      - name: 'Deploy to NAIS q2 team namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss-q2-teamnamespace.yml
          VARS: nais/dev-fss-q2.json
          IMAGE: ${{ env.IMAGE }}