name: Bygg alle brancher

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  bygg:
    name: 'Bygg alle brancher'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v1

      - name: 'Java 11'
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "::set-env name=DATE::$(date "+%Y-%m-%d--%H-%M-%S")"
          echo "::set-env name=COMMIT_HASH::$(git rev-parse HEAD)"

      - name: 'Setter Image'
        run: echo "::set-env name=IMAGE::docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-journalforing:${{ env.DATE }}---${{ env.COMMIT_HASH }}"

      - name: 'Bygg og publiser docker image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ=CET
          ./gradlew build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}

